SELECT  TICKET_TYPE,
        MONTH,
        SUM(REVENUE)/COUNT(DISTINCT DATE),
        SUM(SUM(REVENUE)) OVER (PARTITION BY YEAR
                                    ORDER BY MONTH
                                    ROWS UNBOUNDED PRECEDING),
        (SUM(#SOLD_TICKETS)/SUM(SUM(#SOLD_TICKETS))) * 100 OVER (PARTITION BY MONTH)
FROM TICKET TK, TIME T
WHERE TK.TID = T.TID
GROUP BY TICKET_TYPE, MONTH, YEAR;
