SELECT  MUSEUM,
        TICKET_TYPE,
        SUM(REVENUE)/SUM(#SOLD_TICKETS),
        (SUM(REVENUE)/SUM(SUM(REVENUE))) * 100 OVER (PARTITION BY CATEGORY),
        RANK() OVER (PARTITION BY TICKET_TYPE, MUSEUM
                        ORDER BY SUM(#SOLD_TICKETS) DESC)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND TK.MID = M.MID
    AND YEAR = 2021
GROUP BY MUSEUM, TICKET_TYPE;
