/*
    CREATE MATERIALIZED VIEW
*/

/*
    QUERY 1
*/
SELECT  TICKET_TYPE,
        MONTH,
        SUM(REVENUE)/COUNT(DISTINCT DATE)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND T.MID = M.MID
GROUP BY TICKET_TYPE, MONTH;

/*
    QUERY 2
*/
SELECT  TICKET_TYPE,
        MONTH,
        SUM(SUM(REVENUE)) OVER (PARTITION BY YEAR
                                    ORDER BY MONTH
                                    ROWS UNBOUNDED PRECEDING)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND T.MID = M.MID
GROUP BY TICKET_TYPE, MONTH, YEAR;

/*
    QUERY 3
*/
SELECT  TICKET_TYPE,
        MONTH,
        SUM(REVENUE),
        SUM(#SOLD_TICKETS),
        SUM(REVENUE)/SUM(#SOLD_TICKETS)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND T.MID = M.MID
GROUP BY TICKET_TYPE, MONTH;

/*
    QUERY 4
*/
SELECT  TICKET_TYPE,
        MONTH,
        SUM(REVENUE),
        SUM(#SOLD_TICKETS),
        SUM(REVENUE)/SUM(#SOLD_TICKETS)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND T.MID = M.MID
    AND YEAR = 2021
GROUP BY TICKET_TYPE, MONTH, YEAR;

/*
    QUERY 5
*/
SELECT  TICKET_TYPE,
        MONTH,
        (SUM(#SOLD_TICKETS)/SUM(SUM(#SOLD_TICKETS))) * 100 OVER (PARTITION BY MONTH)
FROM TICKET TK, TIME T, MUSEUM M
WHERE TK.TID = T.TID
    AND T.MID = M.MID
GROUP BY TICKET_TYPE, MONTH;

/*
    MATERIALIZED VIEW
*/
CREATE MATERIALIZED VIEW ViewTicket
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
    SELECT  TICKET_TYPE,
            DATE,
            MONTH,
            YEAR,
            SUM(REVENUE) AS TOT_REVENUE,
            SUM(#SOLD_TICKETS) AS TOT_SOLD_TICKETS
    FROM TICKET TK, TIME T
    WHERE TK.TID = T.TID
    GROUP BY TICKET_TYPE, MONTH, YEAR, DATE;