INSERT INTO VM1(TICKET_TYPE, DATE, MONTH, YEAR, TOT_REVENUE, TOT_SOLD_TICKETS)
(
    SELECT  TICKET_TYPE,
            DATE,
            MONTH,
            YEAR,
            SUM(TOT_REVENUE),
            SUM(SOLD_TICKETS)
    FROM TICKET TK, TIME T
    WHERE TK.TID = T.TID
    GROUP BY TICKET_TYPE, DATE, MONTH, YEAR;
);