/*
    MATERIALIZED VIEW LOG
*/
CREATE MATERIALIZED VIEW LOG ON TICKET
WITH SEQUENCE, ROWID (TKID, TID, MID, TICKET_TYPE, PURCHASE_MODALITY, TIME_SLOT, REVENUE, #SOLD_TICKETS)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TIME
WITH SEQUENCE, ROWID (TID, DATE, MONTH, YEAR)
INCLUDING NEW VALUES;