/*
    TRIGGER FOR UPDATE OF MATERIALIZED VIEW AFTER NEW INSERT ON TICKET
*/

CREATE TRIGGER RefreshViewTicket
AFTER INSERT ON TICKET
FOR EACH ROW

DECLARE

varDate DATE;
varMonth VARCHAR(20);
varYear INTEGER;
N INTEGER;

BEGIN

SELECT DATE, MONTH, YEAR INTO varDate, varMonth, varYear
FROM TIME
WHERE TID = :NEW.TID;

SELECT COUNT(*) INTO N
FROM ViewTicket
WHERE DATE = varDate
    AND TICKET_TYPE = :NEW.TICKET_TYPE

IF (N>0) THEN
-- a record exists and I need to update it
    UPDATE VM1
    SET TOT_REVENUE = TOT_REVENUE + :NEW.REVENUE,
        TOT_SOLD_TICKETS = TOT_SOLD_TICKETS + :NEW.#SOLD_TICKETS
    WHERE DATE = varDate
        AND TICKET_TYPE = :NEW.TICKET_TYPE
ELSE
--I need to insert a new record
    INSERT INTO VM1 (TICKET_TYPE, DATE, MONTH, YEAR, TOT_REVENUE, TOT_SOLD_TICKETS)
    VALUES (:NEW.TICKET_TYPE, varDate, varMonth, varYear, :NEW.REVENUE, :NEW.#SOLD_TICKETS);
END IF;
END;