/* QUERY 1*/
SELECT  PROVINCE,
        MONTH,
        SUM(TOTAL_VALUE),
        SUM(TOTAL_NUMBER)
FROM PRODUCTS P, TIME T, STOREHOUSE SH
WHERE P.TID = T.TID
    AND P.SID = SH.SID
    AND (6M = 1/2015 OR 6M = 1/2016)
    AND REGION = 'Piedmont'
GROUP BY PROVINCE, MONTH;

/* QUERY 2*/
SELECT  PROVINCE,
        6M,
        SUM(TOTAL_VALUE)/COUNT(DISTINCT MONTH)
        --AVG(SUM(TOTAL_VALUE)) OVER (PARTITION BY MONTH)
FROM PRODUCTS P, TIME T, STOREHOUSE SH
WHERE P.TID = T.TID
    AND P.SID = SH.SID
    AND YEAR = 2013
GROUP BY PROVICNE, 6M;

/* QUERY 3*/
SELECT  REGION,
        3M,
        SUM(TOTAL_VALUE)
FROM PRODUCTS P, TIME T, STOREHOUSE SH
WHERE P.TID = T.TID
    AND P.SID = SH.SID
    AND YEAR = 2014
GROUP BY REGION, 3M;

/* MATERIALIZED VIEW */
/* 
    IN SELECT, I INSERT ATTRIBUTES PRESENT IN GROUP BY, AND ALL USEFULL MEASURES (SUM, AVG, ETC...) 
    IN FROM, I INSERT ALL THE TABLES PRESENT IN THE QUERIES.
    IN WHERE, I ONLY INSERT JOIN CONDITIONS.
    IN GROUP BY, FIRSTLY I INSERT ATTRIBUTES WITH LOWER LEVEL CARDINALITY FOR EACH DIMENSION PRESENT IN SELECT,
        AND ALSO THE OTHER ATTRIBUTES PRESENT IN WHERE AND GROUP BY.
 */

SELECT  PROVINCE,
        MONTH,
        REGION,
        3M,
        6M,
        YEAR,
        SUM(TOTAL_VALUE) AS M_TOTAL_VALUE,
        SUM(TOTAL_NUMBER) AS M_TOTAL_NUMBER
FROM PRODUCTS P, TIME T, STOREHOUSE SH
WHERE P.TID = T.TID
    AND P.SID = SH.SID
GROUP BY PROVINCE, MONTH, REGION, 3M, 6M, YEAR;

Identifiers: Province, Month