SELECT  DISTINCT MONTH,
        REGION,
        AVG((SUM(TOTAL_FREE_M2)/SUM(TOTAL_M2))*100) OVER (PARTITION BY REGION, MONTH)
FROM SURFACE S, TIME T, STOREHOUSE SH
WHERE S.SID = SH.SID
    AND S.TID = S.SID
    AND YESR = 2014
GROUP BY MONTH, REGION, DATE;