SELECT  PHONERATETYPE,
        DATEMONTH,
        SUM(PRICE),
        SUM(PRICE)/SUM(SUM(PRICE)) OVER (PARTITION BY PHONERATETYPE),
        SUM(PRICE)/SUM(SUM(PRICE)) OVER (PARTITION BY DATEMONTH)
FROM FACTS F, TIMEDIM T, PHONERATE P
WHERE F.ID_TIME = T.ID_TIME
    AND F.ID_PHONERATE = P.ID_PHONERATE
    AND DATEYEAR = 2003
GROUP BY PHONERATETYPE, DATEMONTH;