SELECT  DATEMONTH,
        PHONERATETYPE,
        LR.REGION,
        LC.REGION
        SUM(NUMBEROFACALLS)
FROM FACTS F, TIMEDIM T, PHONERATE P, LOCATION LC, LOCATION LR
WHERE F.ID_TIME = T.ID_TIME
    AND F.ID_PHONERATE = P.PHONERATE
    AND F.ID_LOCATION_RECEIVER = LR.ID_LOCATION
    AND F.ID_LOCATION_CALLER = LC.ID_LOCATION
    AND DATEYEAR = 2003
GROUP BY GROUPING SETS (DATEMONTH,
                        (DATEMONTH, PHONERATETYPE, LC.CITY),
                        (DATEMONTH, PHONERATETYPE, LR.REGION));