SELECT  PHONERATETYPE,
        DATEYEAR,
        SUM(PRICE),
        SUM(SUM(PRICE)) OVER (PARTITION BY DATEYEAR),
        SUM(SUM(PRICE)) OVER (PARTITION BY PHONERATETYPE),
        SUM(SUM(PRICE)) OVER ()
FROM FACTS F, TIMEDIM T, PHONERATE P
WHERE F.ID_TIME = T.ID_TIME
    AND F.ID_PHONERATE = P.ID_PHONERATE
GROUP BY PHONERATETYPE, DATEYEAR;