SELECT  DATEYEAR,
        DATEMONTH,
        SUM(PRICE),
        SUM(SUM(PRICE)) OVER (PARTITION BY DATEYEAR
                                ORDER BY DATEMONTH
                                ROWS UNBOUNDED PRECEDING)
FROM FACTS F, TIMEDIM T
WHERE F.ID_TIME = T.ID_TIME
GROUP BY DATEMONTH, DATEYEAR;