SELECT  WINE_TYPE,
        RANK() OVER (PARTITION BY COUNTRY
                        ORDER BY SUM(TOT_LITERS) DESC)
FROM EXPORT E, DESTINATION D, WINE_TYPE WT
WHERE E.DID = D.DID
    AND E.WTID = WT.WTID
    AND ORDER_SIZE = 'Large'
GROUP BY WINE_TYPE, COUNTRY;