SELECT  REGION,
        YEAR,
        SUM(TOT_INCOME)/SUM(TOT_LITERS),
        SUM(TOT_LITERS)/COUNT(DISTINCT PROVINCE),
        SUM(TOT_LITERS)/SUM(SUM(TOT_LITERS)) OVER (PARTITION BY GEOGRAPHICAL_AREA, YEAR)
FROM EXPORT E, TIME T, WINERY W
WHERE E.TID = T.TID
    AND E.WID = W.WID
GROUP BY REGION, YEAR, GEOGRAPHICAL_AREA;