/*
    CREATE MATERIALIZED VIEW
*/

/*
    EX 1
*/

/* QUERY 1*/
SELECT  SERVICETYPE,
        SEMESTER,
        SUM(#CONSULTANCIES),
        SUM(INCOME)
FROM INCOME I, TIME T, SERVICE S, CONSULTANTS_BRANCH CB
WHERE I.TIMEID = T.TIMEID
    AND I.SERVICEID = S.SERVICEID
    AND I.BRANCHID = CB.BRANCHID
    AND REGION = 'Lombardy'
GROUP BY SERVICETYPE, SEMESTER;

/* QUERY 2*/
SELECT  SERVICE,
        REGION,
        YEAR,
        SUM(INCOME),
        SUM(#CONSULTANCIES),
FROM INCOME I, TIME T, SERVICE S, COMPANY C
WHERE I.TIMEID = T.TIMEID
    AND I.SERVICEID = S.SERVICEID
    AND I.COMPANYCATEGORYID = C.COMPANYCATEGORYID
    AND (NATIONALITY = 'Italian' OR NATIONALITY = 'German')
GROUP BY SERVICE, REGION, YEAR;

/* QUERY 3*/
SELECT  SERVICETYPE,
        NATIONALITY,
        SEMESTER,
        SUM(INCOME),
        SUM(INCOME)/SUM(#CONSULTANCIES)
FROM INCOME I, TIME T, SERVICE S, COMPANY C, CONSULTANTS_BRANCH CB
WHERE I.TIMEID = T.TIMEID
    AND I.SERVICEID = S.SERVICEID
    AND I.COMPANYCATEGORYID = C.COMPANYCATEGORYID
    AND (YEAR = 2017 OR YEAR = 2018 OR YEAR = 2019)
GROUP BY SERVICETYPE, NATIONALITY, SEMESTER;

/* MATERIALIZED VIEW */
SELECT  SERVICETYPE,
        NATIONALITY,
        SEMESTER,
        SERVICE,
        REGION,
        YEAR,
        SUM(INCOME) AS TOTAL_INCOME,
        SUM(#CONSULTANCIES) AS TOTAL_NUM_CONSULTANCIES
FROM INCOME I, TIME T, SERVICE S, COMPANY C, CONSULTANTS_BRANCH CB
WHERE I.TIMEID = T.TIMEID
    AND I.SERVICEID = S.SERVICEID
    AND I.COMPANYCATEGORYID = C.COMPANYCATEGORYID
    AND I.BRANCHID = CB.BRANCHID
GROUP BY SERVICETYPE, NATIONALITY, SEMESTER, SERVICE, REGION, YEAR;

/*
    EX 2
*/
Identifiers: Service, Semester, Nationality, Region
Service -> ServiceType
Semester -> Year