SELECT  C.CATEGORYNAME,
        SUM(S.NUMSOLDITEMS),
        SUM(S.TOTAMOUNT),
        RANK() OVER (ORDER BY SUM(S.TOTAMOUNT) DESC) AS RANK_TOTAMOUNT,
        RANK() OVER (ORDER BY SUM(S.NUMSOLDITEMS) DESC) AS RANK_NUMSOLDITEMS
FROM SALES S, CATEGORY C
WHERE S.ITEMCATEGORYID = C.CATEGORYID
GROUP BY CATEGORYID, CATEGORYNAME
ORDER BY RANK_NUMSOLDITEMS;